name: Release (snapshot)
on: [ push ]
jobs:
  # todo(James Bradlee): Re-add quality-assurance once IntelliJ fix their stuff.
  # quality-assurance:
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write
  #     packages: read
  #   name: Quality Assurance
  #   uses: ./.github/workflows/quality-assurance.yml
  versioning:
    name: Versioning
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        env:
          GIT_SHA: ${{ github.sha }}
        run: |
          VERSION="${GIT_SHA:0:16}-SNAPSHOT"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "::notice::new version($VERSION)"
  release:
    name: Release (Snapshot)
    runs-on: ubuntu-latest
    # todo(James Bradlee): Re-add quality-assurance once IntelliJ fix their stuff.
    # needs: [ quality-assurance, versioning ]
    needs: [ versioning ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # region todo(James Bradlee): Find an effective way to do this in a different job and
      #                             download the cache and artifacts for immediate release when
      #                             quality assurance is complete.
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Release (packages)
        env:
          VERSION: ${{ needs.versioning.outputs.version }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew publish
      # endregion
